name: Debugging with SSH
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
 
     - name: Try Build
       run: ./not-exist-file.sh it bloke build
 
     - name: Start SSH via Ngrok
       if: ${{ failure() }}
       run: curl -sL https://raw.githubusercontent.com/P3TERX/ssh2actions/main/ngrok2actions.sh | bash
       env:
        # After sign up on the https://ngrok.com/
        # You can find this token here: https://dashboard.ngrok.com/get-started/setup
            NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
    
            # ngrok server region [us, eu, au, ap, sa, jp, in] (optional, default: us)
            # You can find this server region here: https://ngrok.com/docs#global-locations
            NGROK_REGION: us

            # This password you will use when authorizing via SSH
            SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}

            # Send connection info to Telegram (optional)
            # You can find related documents here: https://core.telegram.org/bots
            TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
            TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
 
     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 1h # Prevent to killing instance after failure
